/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teeth;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author popul
 */
public class addSEcretary extends javax.swing.JFrame {

    /**
     * Creates new form addSEcretary
     */
    Connection con;
    PreparedStatement ps;
    ResultSet re;
    private ArrayList<String> arrayAuthorities = new ArrayList<String>();
    private ArrayList<String> arraySecName = new ArrayList<String>();
    private ArrayList<String> arraySecEmail = new ArrayList<String>();

    String nameS = "", password = "", emailS = "", genderS = "", hourS = "";
    int salary = 0;
    java.sql.Date sDate = null;

    public addSEcretary() {
        initComponents();
        con = DBHelper.connect.getConnection();
        this.setDefaultCloseOperation(JFrame.HEIGHT);
        addAuthorities();
        addSecNameAndEmail();
    }

    private void fillComboAuthorities(ArrayList arrayAuthorities) {
        Collections.sort(arrayAuthorities, String.CASE_INSENSITIVE_ORDER);
        for (int i = 0; i < arrayAuthorities.size(); i++) {
            comboAutho.addItem((String) arrayAuthorities.get(i));
        }
    }

    private void addAuthorities() {
        try {
            ps = con.prepareStatement("SELECT authorityName FROM authorities ;");
            re = ps.executeQuery();
            while (re.next()) {
                String authority = re.getString("authorityName");
                arrayAuthorities.add(authority);
            }
            fillComboAuthorities(arrayAuthorities);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillComboSecName(ArrayList arrayName) {
        Collections.sort(arrayName, String.CASE_INSENSITIVE_ORDER);
        for (int i = 0; i < arrayName.size(); i++) {
            comboSecName.addItem((String) arrayName.get(i));
        }
    }

    private void fillComboSecEmail(ArrayList arraySec) {
        Collections.sort(arraySec, String.CASE_INSENSITIVE_ORDER);
        for (int i = 0; i < arraySec.size(); i++) {
            comboEmail.addItem((String) arraySec.get(i));
        }
    }

    private void addSecNameAndEmail() {
        String nameSec = "";
        String emailSec = "";
        try {
            ps = con.prepareStatement("SELECT name,email FROM secretaries ;");
            re = ps.executeQuery();
            while (re.next()) {
                nameSec = re.getString("name");
                emailSec = re.getString("email");
                arraySecName.add(nameSec);
                arraySecEmail.add(emailSec);
            }
            fillComboSecName(arraySecName);
            fillComboSecEmail(arraySecEmail);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSecretary = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        salary1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        txtName6 = new javax.swing.JTextField();
        txtEMail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtHours = new javax.swing.JTextField();
        btnCAncel = new javax.swing.JButton();
        btnSave3 = new javax.swing.JButton();
        hours = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        txtName14 = new javax.swing.JTextField();
        gender1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        addDoctor = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtName12 = new javax.swing.JTextField();
        btncancel4 = new javax.swing.JButton();
        btnSave5 = new javax.swing.JButton();
        email3 = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        DOB1 = new javax.swing.JLabel();
        hours1 = new javax.swing.JLabel();
        txtHours1 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        addAppointment = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        Time = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        comvoDoctor = new javax.swing.JComboBox<>();
        date = new javax.swing.JLabel();
        doctor = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        comboemail = new javax.swing.JComboBox<>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        addAuthorityForSecretary = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        secEmail = new javax.swing.JLabel();
        authority = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnSave7 = new javax.swing.JButton();
        comboEmail = new javax.swing.JComboBox<>();
        secName = new javax.swing.JLabel();
        comboSecName = new javax.swing.JComboBox<>();
        comboAutho = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        newAuthority = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        txtAuthority1 = new javax.swing.JTextField();
        authority1 = new javax.swing.JLabel();
        btncancel1 = new javax.swing.JButton();
        btnSave8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        addSecretary.setLocation(new java.awt.Point(300, 200));
        addSecretary.setMinimumSize(new java.awt.Dimension(458, 490));

        jPanel2.setBackground(new java.awt.Color(247, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 460));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salary1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        salary1.setForeground(new java.awt.Color(51, 51, 255));
        salary1.setText("Salary :");
        jPanel2.add(salary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        email1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        email1.setForeground(new java.awt.Color(51, 51, 255));
        email1.setText("Email :");
        jPanel2.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, 70, -1));

        name1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        name1.setForeground(new java.awt.Color(51, 51, 255));
        name1.setText("Name :");
        jPanel2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        password1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        password1.setForeground(new java.awt.Color(51, 51, 255));
        password1.setText("Password :");
        jPanel2.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtName6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName6ActionPerformed(evt);
            }
        });
        jPanel2.add(txtName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 200, -1));

        txtEMail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        txtHours.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursActionPerformed(evt);
            }
        });
        jPanel2.add(txtHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 200, -1));

        btnCAncel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnCAncel.setForeground(new java.awt.Color(51, 51, 255));
        btnCAncel.setText("Cancel");
        btnCAncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAncelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCAncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, 30));

        btnSave3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnSave3.setForeground(new java.awt.Color(51, 51, 255));
        btnSave3.setText("Save");
        btnSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 80, 30));

        hours.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        hours.setForeground(new java.awt.Color(51, 51, 255));
        hours.setText("Hours :");
        jPanel2.add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        DOB.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        DOB.setForeground(new java.awt.Color(51, 51, 255));
        DOB.setText("Date Of Birth  :");
        jPanel2.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtName14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName14ActionPerformed(evt);
            }
        });
        jPanel2.add(txtName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, -1));

        gender1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        gender1.setForeground(new java.awt.Color(51, 51, 255));
        gender1.setText("Gender :");
        jPanel2.add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton3.setText("Male");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, 30));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton4.setText("Female");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, 30));

        javax.swing.GroupLayout addSecretaryLayout = new javax.swing.GroupLayout(addSecretary.getContentPane());
        addSecretary.getContentPane().setLayout(addSecretaryLayout);
        addSecretaryLayout.setHorizontalGroup(
            addSecretaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        addSecretaryLayout.setVerticalGroup(
            addSecretaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addDoctor.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(247, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4)));
        jPanel3.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(370, 320));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        name2.setForeground(new java.awt.Color(51, 51, 255));
        name2.setText("Name :");
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        gender.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        gender.setForeground(new java.awt.Color(51, 51, 255));
        gender.setText("Gender :");
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        password2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        password2.setForeground(new java.awt.Color(51, 51, 255));
        password2.setText("Password :");
        jPanel3.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel3.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 160, 30));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, 30));

        txtName12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName12ActionPerformed(evt);
            }
        });
        jPanel3.add(txtName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, 30));

        btncancel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btncancel4.setForeground(new java.awt.Color(51, 51, 255));
        btncancel4.setText("Cancel");
        btncancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel4ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 30));

        btnSave5.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnSave5.setForeground(new java.awt.Color(51, 51, 255));
        btnSave5.setText("Save");
        btnSave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 80, 30));

        email3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        email3.setForeground(new java.awt.Color(51, 51, 255));
        email3.setText(" Email :");
        jPanel3.add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup1.add(jRadioMale);
        jRadioMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioMale.setText("Male");
        jPanel3.add(jRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, -1));

        buttonGroup1.add(jRadioFemale);
        jRadioFemale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioFemale.setText("Female");
        jRadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemaleActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        DOB1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        DOB1.setForeground(new java.awt.Color(51, 51, 255));
        DOB1.setText("Date Of Birth  :");
        jPanel3.add(DOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        hours1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        hours1.setForeground(new java.awt.Color(51, 51, 255));
        hours1.setText("Hours :");
        jPanel3.add(hours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtHours1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtHours1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHours1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtHours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, -1));
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 30));

        javax.swing.GroupLayout addDoctorLayout = new javax.swing.GroupLayout(addDoctor.getContentPane());
        addDoctor.getContentPane().setLayout(addDoctorLayout);
        addDoctorLayout.setHorizontalGroup(
            addDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        addDoctorLayout.setVerticalGroup(
            addDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(247, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4)));
        jPanel4.setForeground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Time.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        Time.setForeground(new java.awt.Color(51, 51, 255));
        Time.setText("Time :");
        jPanel4.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, 30));

        btnCancel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 51, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        btnSave.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 51, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 80, 30));

        email.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 255));
        email.setText("Doctor 's Email :");
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 200, -1, -1));

        comvoDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comvoDoctorActionPerformed(evt);
            }
        });
        jPanel4.add(comvoDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 130, -1));

        date.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        date.setText("Date :");
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 120, -1, -1));

        doctor.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        doctor.setForeground(new java.awt.Color(51, 51, 255));
        doctor.setText("Doctor 's Name :");
        jPanel4.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 160, -1, -1));

        name.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 255));
        name.setText("Name :");
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel4.add(comboemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 205, 130, 20));
        jPanel4.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, 30));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 30));

        javax.swing.GroupLayout addAppointmentLayout = new javax.swing.GroupLayout(addAppointment.getContentPane());
        addAppointment.getContentPane().setLayout(addAppointmentLayout);
        addAppointmentLayout.setHorizontalGroup(
            addAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAppointmentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addAppointmentLayout.setVerticalGroup(
            addAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        addAuthorityForSecretary.setMinimumSize(new java.awt.Dimension(442, 392));

        jPanel5.setBackground(new java.awt.Color(247, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4)));
        jPanel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secEmail.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        secEmail.setForeground(new java.awt.Color(51, 51, 255));
        secEmail.setText("Secretary Email :");
        jPanel5.add(secEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        authority.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        authority.setForeground(new java.awt.Color(51, 51, 255));
        authority.setText("Authority :");
        jPanel5.add(authority, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        btncancel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(51, 51, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        btnSave7.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnSave7.setForeground(new java.awt.Color(51, 51, 255));
        btnSave7.setText("Save");
        btnSave7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave7ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 80, 30));

        comboEmail.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        comboEmail.setForeground(new java.awt.Color(51, 51, 255));
        comboEmail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose..." }));
        jPanel5.add(comboEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, 30));

        secName.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        secName.setForeground(new java.awt.Color(51, 51, 255));
        secName.setText("Secretary Name :");
        jPanel5.add(secName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        comboSecName.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        comboSecName.setForeground(new java.awt.Color(51, 51, 255));
        comboSecName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose..." }));
        jPanel5.add(comboSecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, 30));

        comboAutho.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        comboAutho.setForeground(new java.awt.Color(51, 51, 255));
        comboAutho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose..." }));
        jPanel5.add(comboAutho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 220, 30));

        javax.swing.GroupLayout addAuthorityForSecretaryLayout = new javax.swing.GroupLayout(addAuthorityForSecretary.getContentPane());
        addAuthorityForSecretary.getContentPane().setLayout(addAuthorityForSecretaryLayout);
        addAuthorityForSecretaryLayout.setHorizontalGroup(
            addAuthorityForSecretaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorityForSecretaryLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        addAuthorityForSecretaryLayout.setVerticalGroup(
            addAuthorityForSecretaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAuthorityForSecretaryLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        newAuthority.setMinimumSize(new java.awt.Dimension(372, 276));

        jPanel6.setBackground(new java.awt.Color(247, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4)));
        jPanel6.setForeground(new java.awt.Color(0, 0, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(382, 293));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAuthority1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtAuthority1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthority1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtAuthority1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, -1));

        authority1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        authority1.setForeground(new java.awt.Color(51, 51, 255));
        authority1.setText("Authority :");
        jPanel6.add(authority1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btncancel1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btncancel1.setForeground(new java.awt.Color(51, 51, 255));
        btncancel1.setText("Cancel");
        btncancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel1ActionPerformed(evt);
            }
        });
        jPanel6.add(btncancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, 30));

        btnSave8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        btnSave8.setForeground(new java.awt.Color(51, 51, 255));
        btnSave8.setText("Add");
        btnSave8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave8ActionPerformed(evt);
            }
        });
        jPanel6.add(btnSave8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 30));

        javax.swing.GroupLayout newAuthorityLayout = new javax.swing.GroupLayout(newAuthority.getContentPane());
        newAuthority.getContentPane().setLayout(newAuthorityLayout);
        newAuthorityLayout.setHorizontalGroup(
            newAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        newAuthorityLayout.setVerticalGroup(
            newAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(35, 35, 35, 35, new javax.swing.ImageIcon(getClass().getResource("/picture/smaller.png")))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(224, 224, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 72, -1));

        buttonGroup3.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 15)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton1.setText("             Doctor");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 64, 280, -1));

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 15)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton2.setText("             Secretary");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 109, 280, -1));

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 15)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton5.setText("           Authorities For Secretary");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 250, 280, -1));

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 15)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton6.setText("            New Authorities");
        jRadioButton6.setActionCommand("          New Authorities");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 205, 280, -1));

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 15)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton7.setText("            Appointment");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 160, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName6ActionPerformed

    private void txtEMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMailActionPerformed

    private void txtHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursActionPerformed

    private void btnCAncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAncelActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setEnabled(true);
        jRadioButton6.setEnabled(true);
        jRadioButton7.setEnabled(true);
        jRadioButton5.setEnabled(true);
        addSecretary.setVisible(false);
    }//GEN-LAST:event_btnCAncelActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtName12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName12ActionPerformed

    private void btncancel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btncancel4ActionPerformed

    private void jRadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFemaleActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    
        addAuthorityForSecretary.setVisible(false);
        
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtName14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName14ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    // TODO add your handling code here:

    private void txtHours1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHours1ActionPerformed
    }//GEN-LAST:event_txtHours1ActionPerformed
    private Boolean chickTextsSec() {
        if (txtName6.getText().length() > 50 || txtpass.getText().length() > 20 || txtEMail.getText().length() > 50
                || txtHours.getText().length() > 11 || txtName14.getText().length() > 5) {
            return true;
        } else {
            return false;
        }
    }

    private Boolean chickName(String names) {
        Boolean v = true;
        for (int i = 0; i < names.length(); i++) {
            if (names.charAt(i) == ' ') {
                continue;
            }
            if (!Character.isLetter(names.charAt(i))) {
                v = false;
                break;
            }
        }
        return v;
    }

    private Boolean chickEmail(String em) {

        return true;
    }

    private Boolean chickHour(String ho) {

        return true;
    }

    private Boolean chickRadio() {
        if (!jRadioButton3.isSelected() && !jRadioButton4.isSelected()) {
            return true;
        } else {
            return false;
        }
    }

    private Boolean IsRepeatedEmail(String email) {
        Boolean b = false;
        String em = "";
        try {
            ps = con.prepareStatement("SELECT email FROM secretaries;");
            re = ps.executeQuery();
            while (re.next()) {
                em = re.getString("email");
                if (em.equals(email)) {
                    b = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(addSEcretary.class.getName()).log(Level.SEVERE, null, ex);
        }

        return b;
    }

    private static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
    private void btnSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave3ActionPerformed
        // TODO add your handling code here:
        nameS = txtName6.getText().trim();
        emailS = txtEMail.getText().trim();
        password = txtPass.getText().trim();
        hourS = txtHours.getText().trim();
        java.sql.Date sDate = null;
        String b = "";
        try {
            java.util.Date uDate = jDateChooser1.getDate();
            sDate = convertUtilToSql(uDate);////مثودالتحويل في الاسفل  
        } catch (NullPointerException e) {
            b = "empty";
        }
        if (nameS.equals("") || emailS.equals("") || password.equals("") || txtName14.equals("")
                || txtHours.equals("") || chickRadio() || b.equals("empty")) {
            JOptionPane.showMessageDialog(null, "Enter All Information...");
        } else {
            if (chickTextsSec()) {
                JOptionPane.showMessageDialog(null, "Chick Texts ,There Text Contains Too Long Data..\n(Data Length at maximum case Must Be..name(50),password(20), email(50),hours(5),salary(5)");
            } else {
                if (chickName(nameS) == false || chickEmail(emailS) == false || chickHour(hourS) == false) {
                    if (chickName(nameS) == false) {
                        JOptionPane.showMessageDialog(null, "Chick Name, Write Name Without Numbers Or Signs");
                        txtName6.setText("");
                    } else if (chickEmail(emailS) == false) {
                        JOptionPane.showMessageDialog(null, "Chick Email, Write Email in correct order ");
                    } else {
                        JOptionPane.showMessageDialog(null, "Chick hour ,write hour in correct order )");
                    }
                } else {
                    if (IsRepeatedEmail(emailS)) {
                        JOptionPane.showMessageDialog(null, "This Email Is used... ");
                    } else {
                        try {
                            if (jRadioButton3.isSelected()) {
                                genderS = jRadioButton3.getText();
                            } else {
                                genderS = jRadioButton4.getText();
                            }
                            salary = Integer.parseInt(txtName14.getText().trim());
                            try {
                                ps = con.prepareStatement("INSERT INTO  secretaries (name,gender,dateOfBirth,email,salary,password,hours) VALUES(?,?,?,?,?,?);");
                                ps.setString(1, nameS);
                                ps.setString(2, genderS);
                                ps.setDate(3, sDate);
                                ps.setString(4, emailS);
                                ps.setInt(5, salary);
                                ps.setString(6, password);
                                ps.setString(7, hourS);
                                ps.executeUpdate();
                                JOptionPane.showMessageDialog(null, "        Done      ");

                            } catch (SQLException ex) {
                                Logger.getLogger(addSEcretary.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Enter Valid Number...");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSave3ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mainFream().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave5ActionPerformed

    private void comvoDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comvoDoctorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comvoDoctorActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        addDoctor.setResizable(false);
        addSecretary.setAlwaysOnTop(true);
        jRadioButton6.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton2.setEnabled(false);
        addDoctor.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        addSecretary.setResizable(false);
        addSecretary.setAlwaysOnTop(true);
        jRadioButton1.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton6.setEnabled(false);
        addSecretary.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtAuthority1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthority1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthority1ActionPerformed

    private void btncancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel1ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton7.setEnabled(true);
        jRadioButton2.setEnabled(true);
        newAuthority.setVisible(false);
    }//GEN-LAST:event_btncancel1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        addAuthorityForSecretary.setResizable(false);
        addSecretary.setAlwaysOnTop(true);
        jRadioButton1.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton2.setEnabled(false);
        addAuthorityForSecretary.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        newAuthority.setResizable(false);
        addSecretary.setAlwaysOnTop(true);
        jRadioButton1.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton2.setEnabled(false);
        newAuthority.setVisible(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        addAppointment.setResizable(false);
        addSecretary.setAlwaysOnTop(true);
        jRadioButton1.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton2.setEnabled(false);
        addAppointment.setVisible(true);
    }//GEN-LAST:event_jRadioButton7ActionPerformed
    private Boolean chickTextsAuthority(String athuo) {
        if (athuo.length() > 100) {
            return true;
        } else {
            return false;
        }
    }

    private void btnSave7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave7ActionPerformed

        String athuority = comboAutho.getSelectedItem().toString().trim();
        nameS = comboSecName.getSelectedItem().toString().trim();
        emailS = comboEmail.getSelectedItem().toString().trim();
        int ID_secretary = 0;
        String na = "", em = "";
        int ID_authority = 0;
        String auth = "";
        Boolean found=true;
        if (authority.equals("") || nameS.equals("choose...") || emailS.equals("choose...")) {
            JOptionPane.showMessageDialog(null, "Enter All Information...");
        } else {
            try {
                ps = con.prepareStatement("SELECT ID,name,email FROM secretaries;");
                re = ps.executeQuery();
                while (re.next()) {
                    em = re.getString("email");
                    na = re.getString("name");
                    if (na.equals(nameS)) {
                        if (em.equals(emailS)) {
                            ID_secretary = re.getInt("ID");
                            break;
                        }
                    }
                }
                ps = con.prepareStatement("SELECT ID,authorityName FROM authorities;");
                re = ps.executeQuery();
                while (re.next()) {
                    auth = re.getString("authorityName");
                    if (auth.equals(athuority)) {
                        ID_authority = re.getInt("ID");
                        break;
                    }
                }
////                ps = con.prepareStatement("INSERT INTO secretaryauthority(ID_secretary,ID_authority)VALUES(?,?);");
////                ps.setInt(1, ID_secretary);
////                ps.setInt(2, ID_authority);
////                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "       Done      ");

            } catch (SQLException ex) {
                Logger.getLogger(addSEcretary.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSave7ActionPerformed

    private void btnSave8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave8ActionPerformed
        // TODO add your handling code here:
        String newAuth = txtAuthority1.getText().trim();
        String ath="";
        Boolean found = false;
        if (newAuth.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Text...");
        } else {
            if (chickTextsAuthority(newAuth)) {
                JOptionPane.showMessageDialog(null, "Chick Text, Contains Too Long Data..\n(Data Length Must Be..Authority(100 ");
            } else {
                if (!chickName(newAuth)) {
                    JOptionPane.showMessageDialog(null, "Chick Type (Write It Without Numbers Or Signs... )");
                } else {
                    try {
                        ps = con.prepareStatement("SELECT authorityName FROM authorities;");
                        re = ps.executeQuery();
                        while (re.next()) {
                            ath = re.getString("authorityName");
                            if (ath.equals(newAuth)) {
                                found = true;
                                break;
                            }
                        }
                        if (found == false) {
                            ps = con.prepareStatement("INSERT INTO authorities (authorityName) VALUES(?);");
                            ps.setString(1, newAuth);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "New Authority Is Added...");
                            txtAuthority1.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "This Authority Be Found...");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(addSEcretary.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSave8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSEcretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSEcretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSEcretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSEcretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSEcretary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DOB1;
    private javax.swing.JLabel Time;
    private javax.swing.JDialog addAppointment;
    private javax.swing.JDialog addAuthorityForSecretary;
    private javax.swing.JDialog addDoctor;
    private javax.swing.JDialog addSecretary;
    private javax.swing.JLabel authority;
    private javax.swing.JLabel authority1;
    private javax.swing.JButton btnCAncel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave3;
    private javax.swing.JButton btnSave5;
    private javax.swing.JButton btnSave7;
    private javax.swing.JButton btnSave8;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncancel1;
    private javax.swing.JButton btncancel4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboAutho;
    private javax.swing.JComboBox<String> comboEmail;
    private javax.swing.JComboBox<String> comboSecName;
    private javax.swing.JComboBox<String> comboemail;
    private javax.swing.JComboBox<String> comvoDoctor;
    private javax.swing.JLabel date;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JLabel hours;
    private javax.swing.JLabel hours1;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JDialog newAuthority;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel salary1;
    private javax.swing.JLabel secEmail;
    private javax.swing.JLabel secName;
    private javax.swing.JTextField txtAuthority1;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtHours1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName12;
    private javax.swing.JTextField txtName14;
    private javax.swing.JTextField txtName6;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
}
