/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teeth;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author alanwar
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection con = null;
    private ArrayList<String> array = new ArrayList<String>();
    PreparedStatement ps = null;
    ResultSet re;

    public login() {
        initComponents();
        con = DBHelper.connect.getConnection();
        this.setLocation(400, 200);
        addEmails();
        AutoCompleteDecorator.decorate(jComboBox1);
    }

    private void fillCombo(ArrayList array) {
        Collections.sort(array, String.CASE_INSENSITIVE_ORDER);
        for (int i = 0; i < array.size(); i++) {
            jComboBox1.addItem((String) array.get(i));
        }
    }

    private void addEmails() {
        try {
            ps = con.prepareStatement("SELECT email FROM doctors ;");
            re = ps.executeQuery();
            while (re.next()) {
                String emailD = re.getString("email");
                array.add(emailD);
            }
            ps = con.prepareStatement("SELECT email FROM secretaries ;");
            re = ps.executeQuery();
            while (re.next()) {
                String emailS = re.getString("email");
                array.add(emailS);
            }
            fillCombo(array);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(40, 40, 40, 40, new javax.swing.ImageIcon(getClass().getResource("/picture/5502f46c5f7a7af9be9841c4515cbf70.png")))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(424, 272));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 225, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText(" Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText(" Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 103, 38));

        jPasswordField1.setForeground(new java.awt.Color(204, 0, 0));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 30));

        jComboBox1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose..." }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 85, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private Boolean chickTexts(String s) {
        if (s.length() > 20) {
            return true;
        } else {
            return false;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = jComboBox1.getSelectedItem().toString().trim();
        String password = jPasswordField1.getText().trim();
        String em = "";
        String pas = "";
        int i = 0;
        if (email.equals("Choose...") && password.equals("")) {
            JOptionPane.showMessageDialog(null, "Email Text And Password Text Are Empty ,Enter Email And Password...  ");
        } else if (email.equals("Choose...")) {
            JOptionPane.showMessageDialog(null, "Email Text Is Empty ,Enter Eamil...");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password Text Is Empty ,Enter Password...");
        } else {
            try {
                if (chickTexts(password)) {
                    JOptionPane.showMessageDialog(null, "Chick Texs ,Password Text Contains too Long Data (Data Length Must Be password(20))");
                } else {
                    ps = con.prepareStatement("SELECT * FROM doctors;");
                    re = ps.executeQuery();
                    while (re.next()) {
                        em = re.getString("email");
                        pas = re.getString("password");
                        if (em.equals(email)) {
                            i = 1;
                            if (pas.equals(password)) {
                                new mainFream().setVisible(true);
                                this.setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Your Password Is Not correct , Enter Vaild Passwored");
                                jPasswordField1.setText("");
                            }
                        }
                    }
                    if (i == 0) {
                        em = "";
                        pas = "";
                        ps = con.prepareStatement("SELECT * FROM secretaries;");
                        re = ps.executeQuery();
                        while (re.next()) {
                            em = re.getString("email");
                            pas = re.getString("password");
                            if (em.equals(email)) {
                                if (pas.equals(password)) {
                                    new secMain().setVisible(true);
                                    this.setVisible(false);
                                } else {
                                    JOptionPane.showMessageDialog(null, "Your Password Is Not correct , Enter Vaild Passwored");
                                    jPasswordField1.setText("");
                                }
                            }
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
